version: "3.8"
services:
  app:
    container_name: deepsirius-ui
    platform: "linux/amd64"
    build:
      context: .
      dockerfile: ./apps/deepsirius-ui/Dockerfile
      args:
        # build time variables
        # only NEXT_PUBLIC variables needed?
        NEXT_PUBLIC_STORAGE_PATH: "${NEXT_PUBLIC_STORAGE_PATH}"
    working_dir: /app
    volumes:
      - ./server.cer:${CA_CERT}:ro
      - ./apps/deepsirius-ui/prisma/db.sqlite:/app/apps/deepsirius-ui/prisma/db.sqlite:rw
    ports:
      - "3000:3000"
    image: deepsirius-ui/latest
    environment:
      # run time variables
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - LDAP_URI=${LDAP_URI}
      - SSH_HOST=${SSH_HOST}
      - CA_CERT=${CA_CERT}
      - DATABASE_URL=${DATABASE_URL}
      - PRIVATE_KEY_PASSPHRASE=${PRIVATE_KEY_PASSPHRASE}
      - PROCESSING_CONTAINER_PATH=${PROCESSING_CONTAINER_PATH}
      - PROCESSING_CONTAINER_STORAGE_BIND=${PROCESSING_CONTAINER_STORAGE_BIND}
