services:
  app:
    network_mode: 'host'
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .
      dockerfile: dev.Dockerfile
      args:
        NEXTAUTH_URL: ${NEXTAUTH_URL}
        NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
        LDAP_URI: ${LDAP_URI}
        SSH_HOST: ${SSH_HOST}
        CA_CERT: ${CA_CERT}
        CA_CERT_HOST: ${CA_CERT_HOST}
        DATABASE_URL: ${DATABASE_URL}
        PRIVATE_KEY_PASSPHRASE: ${PRIVATE_KEY_PASSPHRASE}
        NEXT_PUBLIC_TREE_PATH: ${NEXT_PUBLIC_TREE_PATH}
    working_dir: /app
    volumes:
      - type: bind
        source: ${DOCKER_HOST_TREE_PATH}
        target: ${NEXT_PUBLIC_TREE_PATH}
      - type: bind
        source: ./src
        target: /app/src
      - type: bind
        source: ./public
        target: /app/public
    restart: always
    ports:
      - 3000:3000
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - LDAP_URI=${LDAP_URI}
      - SSH_HOST=${SSH_HOST}
      - CA_CERT=${CA_CERT}
      - DATABASE_URL=${DATABASE_URL}
      - PRIVATE_KEY_PASSPHRASE=${PRIVATE_KEY_PASSPHRASE}
      - NEXT_PUBLIC_TREE_PATH=${NEXT_PUBLIC_TREE_PATH}

  db:
    image: postgres:15.0
    restart: always
    environment:
      - POSTGRES_USER=fofo
      - POSTGRES_PASSWORD=fofinho
    volumes:
      - type: volume
        source: postgres
        target: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'fofo']
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres:
