version: '3.8'
services:
  app:
    platform: 'linux/amd64'
    network_mode: 'host'
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_TREE_PATH: '${NEXT_PUBLIC_TREE_PATH}'
    working_dir: /app
    volumes:
      - /home:/mnt
    ports:
      - '3000:3000'
    image: deepsirius-ui
    environment:
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - LDAP_URI=${LDAP_URI}
      - SSH_HOST=${SSH_HOST}
      - CA_CERT=${CA_CERT}
      - DATABASE_URL=${DATABASE_URL}
      - PRIVATE_KEY_PASSPHRASE=${PRIVATE_KEY_PASSPHRASE}

  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_USER=fofo
      - POSTGRES_PASSWORD=fofinho
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
